version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "29418:29418"
    depends_on:
      - gerrit
      - jenkins
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log:/var/log/nginx

  gerrit:
    image: gerritcodereview/gerrit
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - CANONICAL_WEB_URL=http://review.test.netease.com/gerrit
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./gerrit/etc:/var/gerrit/etc
      - ./gerrit/git:/var/gerrit/git
      - ./gerrit/index:/var/gerrit/index
      - ./gerrit/cache:/var/gerrit/cache
      - ./gerrit/plugins:/var/gerrit/plugins
      - ./gerrit/logs:/var/gerrit/logs
  #  entrypoint: java -jar /var/gerrit/bin/gerrit.war init -d /var/gerrit

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=gerrit
      - POSTGRES_PASSWORD=basecloud@netease
      - POSTGRES_DB=gerrit_db
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./postgres:/var/lib/postgresql/data

  # mysql:
  #   image: mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=basecloud@netease
  #     - MYSQL_DATABASE=gerrit_db
  #     - MYSQL_USER=gerrit
  #     - MYSQL_PASSWORD=basecloud@netease
  #     - MYSQL_ROOT_HOST=%
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #     - ./mysql/data:/var/lib/mysql
  #     - ./mysql/etc:/etc/mysql/conf.d

  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./jenkins_home:/var/jenkins_home
